### PR TITLE
#CP-9 feat: roles and permissions

### PR DESCRIPTION
**Pull request by feyton**
:arrow_right: :arrow_right: The permissions and roles are strict for :thumbsdown: **`[C|R|U|D]`** which means allowed requests are 
```js
CREATE | POST
READ | GET
UPDATE| PUT
DELETE | DELETE
```
Avoid using other types such as :thumbsdown: **PATCH** when using the permission check.

### What does this PR do?

- [x] Administrator should be able to **[C|R|U|D]** roles
- [x] The administrator should be able to set and update role's permissions
- [x] Access control has been implemented and put in place
- [x] Appropriate error message are displayed on unsuccessful attempts.

### Description of Task to be completed
As **an administrator**, I want to be able to create the role and set its permissions, so that different users can only access & perform data/operations to which they are authorized.

**Roles**

- Driver
- Operator
- Administrator
> Refer to this [Trello Card](https://trello.com/c/cfsTKeAY) for extended overview of the background
### How should this be manually tested?
Since roles are granted and checked on user basis.
> There are no required additional environment configuration to test these roles just remember to `npm install` when you get to it. 

### Postman
To navigate the tests, create the users with different roles (**Note that this feature will be removed in the future**). **[admin, driver, operator]. And with the information from the above mentioned roles and their permissions can be found in the linked **Trello card**. Use the listed routes bellow in postman to tests how protection work.
> **Special attention**: To check for attribute based roles and permissions. Pay more attention on the attributes of the data that you will get back. Since this matters a lot.
> Protected resources are: **[`drivers, operators, routes, companies`]** users are used for testing purpose only in this PR.

#### Testing routes:
```js
// remember to add your host like <http://localhost:<PORT>>
//create an account with role property among [admin, driver, operator] if no role passed, it default to user
POST: /api/v1/users   =>{...info, role:(admin|driver|operator)

// Drivers
(C|R|U|D): /api/v1/drivers
(C|R|U|D): /api/v1/drivers/1234

// operators **Operator|Admin**
(C|R|U|D): /api/v1/operators
(C|R|U|D): /api/v1/operatots/1234

// companies **Admin only**
(C|R|U|D): /api/v1/companies
(C|R|U|D): /api/v1/companies/1234

```
[Run in Postman](https://app.getpostman.com/run-collection/19126547-9b063390-df96-4fff-ba14-af8649100478?action=collection%2Ffork&collection-url=entityId%3D19126547-9b063390-df96-4fff-ba14-af8649100478%26entityType%3Dcollection%26workspaceId%3D252017b1-dc09-4cf8-ad20-ea23c74ad4d7)
### Any background context you want to provide?
Access control is being handled by a really great package that you can access here:
> [AccessControlPackage](https://github.com/onury/accesscontrol#guide)
### What are the relevant pivotal tracker stories?
- [#CP-9](https://trello.com/c/cfsTKeAY)
### Screenshots (if appropriate)

### CODE REVIEW

**Review by Yvad60 — DISMISSED** [review]
Good job with creating roles and setting permissions most of the functionality are there (in the codebase) but I have noticed some errors in the login workflow s where a user can't log in using the system as the server is returning a 500 error. those errors  are making testing roles part implementation in postman not work altogether
try to look into that

**Comment by Abdulkeza** [comment]
great job fab! left some coments

**Comment by Abdulkeza** [comment]
> Good job with creating roles and setting permissions most of the functionality are there (in the codebase) but I have noticed some errors in the login workflow s where a user can't log in using the system as the server is returning a 500 error. those errors are making testing roles part implementation in postman not work altogether try to look into that



> Good job with creating roles and setting permissions most of the functionality are there (in the codebase) but I have noticed some errors in the login workflow s where a user can't log in using the system as the server is returning a 500 error. those errors are making testing roles part implementation in postman not work altogether try to look into that



> Good job with creating roles and setting permissions most of the functionality are there (in the codebase) but I have noticed some errors in the login workflow s where a user can't log in using the system as the server is returning a 500 error. those errors are making testing roles part implementation in postman not work altogether try to look into that

have you tested carefully? it looks like you are testing in wrong way

**Comment by Yvad60** [comment]
> 

I forgot to load all required environment variables

**Review by Abdulkeza — APPROVED** [review]
working perfectly

**Review by samyshyaka — APPROVED** [review]
This is a good implementation @feyton. When I log in as an admin I'm able to access all resources, as an operator, I can access the drivers and limited attributes of other operators and as a driver I can access limited attributes of other drivers.

**Pull request merged**
